### ISSUE TITLE
How to get started with this repo

### ISSUE THREAD

**Issue by Said1996** [jpmikkers/Baksteen.Avalonia.Blazor#4]
I didn't find any nuget package for this repo, nor do I understand how to make it work ...
I would be grateful for any guide

**Comment by jpmikkers** [comment]
I waiting with releasing the package on nuget.org until avalonia 11 gets a final release.
In the mean time, you can clone the repo and build the solution, it contains both the package and the demo app.

**Comment by Said1996** [comment]
Thanks
